<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Andrey Prado and Diego Vega">

<title>Pruebas de Hipótesis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="PruebasHipotesis_files/libs/clipboard/clipboard.min.js"></script>
<script src="PruebasHipotesis_files/libs/quarto-html/quarto.js"></script>
<script src="PruebasHipotesis_files/libs/quarto-html/popper.min.js"></script>
<script src="PruebasHipotesis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="PruebasHipotesis_files/libs/quarto-html/anchor.min.js"></script>
<link href="PruebasHipotesis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="PruebasHipotesis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="PruebasHipotesis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="PruebasHipotesis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="PruebasHipotesis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pruebas de Hipótesis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Andrey Prado and Diego Vega </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="pruebas-de-hipótesis-que-se-utilizarán" class="level3">
<h3 class="anchored" data-anchor-id="pruebas-de-hipótesis-que-se-utilizarán">Pruebas de Hipótesis que se utilizarán</h3>
<p>El objetivo de la aplicación de las pruebas en el presente trabajo es el de verificar la independencia de las variables y la relación entre las observaciones de Febrero y Julio para justificar la posterior elección del modelo, entre las opciones principales están XGBoost, LGBM, Modelo Lasso, Regresión Lineal, entre otras.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prueba de Shapiro-Wilk
</div>
</div>
<div class="callout-body-container callout-body">
<p>La prueba de Shapiro-Wilk es una prueba estadística utilizada para determinar si una muestra de datos sigue una distribución normal. Es una prueba de bondad de ajuste que evalúa qué tan cerca se ajustan los datos de la muestra a una distribución normal. La hipótesis nula de la prueba es que la muestra proviene de una población distribuida normalmente.</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seleccionar solo variables numéricas</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>vars_numericas <span class="ot">&lt;-</span> base[, <span class="fu">sapply</span>(base, is.numeric)]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Inicializar listas para resultados</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>nombres <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>p_values <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>es_normal <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar prueba de Shapiro-Wilk a cada variable numérica</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (nombre <span class="cf">in</span> <span class="fu">names</span>(vars_numericas)) {</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  variable <span class="ot">&lt;-</span> vars_numericas[[nombre]]</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  variable <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(variable)  <span class="co"># Omitir NA</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Verificar condiciones para aplicar la prueba</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(variable) <span class="sc">&gt;=</span> <span class="dv">3</span> <span class="sc">&amp;&amp;</span> <span class="fu">length</span>(<span class="fu">unique</span>(variable)) <span class="sc">&gt;</span> <span class="dv">1</span>) {</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    prueba <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(variable)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    nombres <span class="ot">&lt;-</span> <span class="fu">c</span>(nombres, nombre)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    p_values <span class="ot">&lt;-</span> <span class="fu">c</span>(p_values, prueba<span class="sc">$</span>p.value)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    es_normal <span class="ot">&lt;-</span> <span class="fu">c</span>(es_normal, prueba<span class="sc">$</span>p.value <span class="sc">&gt;</span> <span class="fl">0.05</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Registrar variables que no cumplen condiciones</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    nombres <span class="ot">&lt;-</span> <span class="fu">c</span>(nombres, nombre)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    p_values <span class="ot">&lt;-</span> <span class="fu">c</span>(p_values, <span class="cn">NA</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    es_normal <span class="ot">&lt;-</span> <span class="fu">c</span>(es_normal, <span class="cn">NA</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Mensaje informativo</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">length</span>(<span class="fu">unique</span>(variable)) <span class="sc">==</span> <span class="dv">1</span>) {</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>      <span class="fu">message</span>(<span class="fu">paste</span>(<span class="st">"Variable"</span>, nombre, <span class="st">"tiene todos sus valores idénticos. Prueba omitida."</span>))</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> <span class="cf">if</span> (<span class="fu">length</span>(variable) <span class="sc">&lt;</span> <span class="dv">3</span>) {</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>      <span class="fu">message</span>(<span class="fu">paste</span>(<span class="st">"Variable"</span>, nombre, <span class="st">"tiene menos de 3 observaciones. Prueba omitida."</span>))</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear data frame resumen</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>resumen_normalidad <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> nombres,</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_value =</span> <span class="fu">round</span>(p_values, <span class="dv">4</span>),</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">Es_Normal =</span> es_normal</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>kableExtra<span class="sc">::</span><span class="fu">kable</span>(resumen_normalidad)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">p_value</th>
<th style="text-align: left;">Es_Normal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">profundidad</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">salinidad</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">oxigeno</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">sat_oxigen</td>
<td style="text-align: right;">0.0029</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">precipitacionf</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">tempairef</td>
<td style="text-align: right;">0.6552</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">precipitacionj</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">tempaguaj</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">tempairej</td>
<td style="text-align: right;">0.3049</td>
<td style="text-align: left;">TRUE</td>
</tr>
<tr class="even">
<td style="text-align: left;">colifecalj</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ecolij</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">enterococoj</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ph</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">fosfatos</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">silicatos</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">amonio</td>
<td style="text-align: right;">0.0269</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nitritos</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">nitratos</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">chla_agua</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">faopigmentos</td>
<td style="text-align: right;">0.0002</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">matsuspension</td>
<td style="text-align: right;">0.0252</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">alcali_total</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dureza</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">carbonatos</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">zinc</td>
<td style="text-align: right;">0.0101</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">cobre</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ca2</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">mg2</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">na</td>
<td style="text-align: right;">0.0003</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">k</td>
<td style="text-align: right;">0.0004</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cl</td>
<td style="text-align: right;">0.0001</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">SO42</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dbof</td>
<td style="text-align: right;">0.0206</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">dboj</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dqof</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">dqoj</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="odd">
<td style="text-align: left;">latitud</td>
<td style="text-align: right;">0.0024</td>
<td style="text-align: left;">FALSE</td>
</tr>
<tr class="even">
<td style="text-align: left;">longitud</td>
<td style="text-align: right;">0.0140</td>
<td style="text-align: left;">FALSE</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Este código realiza la prueba de normalidad de Shapiro-Wilk a todas las variables numéricas del conjunto de datos base_agua_limpia. Primero, se seleccionan únicamente las columnas numéricas y luego se aplica la prueba individualmente a cada una. Para cada variable: - Si tiene al menos 3 observaciones sin valores perdidos y más de un valor único, se realiza la prueba de Shapiro-Wilk. - Se registra el nombre de la variable, su valor p y si se considera que sigue una distribución normal (TRUE si p &gt; 0.05, FALSE en caso contrario). - Si una variable tiene menos de 3 datos o todos sus valores son idénticos, se omite la prueba y se muestra un mensaje informativo.</p>
<p>Finalmente, los resultados se presentan en un data frame llamado resumen_normalidad, donde se listan todas las variables evaluadas junto con su valor p y un indicador lógico que señala si la distribución se considera normal bajo el nivel de significancia del 5%.</p>
<p>El resultado muestra que solo dos variables (tempairef y tempairej) siguen una distribución normal, mientras que las demás no superan la prueba. Una variable (cobre) no pudo evaluarse por contener datos insuficientes o no adecuados.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prueba de Wilcoxon pareada
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta prueba determina si dos grupos dependientes difieren en distribución entre sí. Dicha prueba utiliza los rangos de los grupos en lugar de los valores medios. A diferencia de la prueba t pareada, esta es una prueba no paramétrica por lo tanto en cuanto se dejen de cumplir las condiciones de uso de la prueba t (normalidad de los datos) como en este caso se utiliza esta prueba. Los supuestos que se deben cumplir para la realización de la prueba son: - Medición Repetida, es decir que una característica se mida en dos momentos distintos - Parejas, es decir los datos no necesariamente deben ser la misma observación si no que pertenezcan a los dos grupos que se están analizando.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(base<span class="sc">$</span>dbof, base<span class="sc">$</span>dboj, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(base$dbof, base$dboj, paired = TRUE): cannot
compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  base$dbof and base$dboj
V = 98, p-value = 0.01731
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(base<span class="sc">$</span>dqof, base<span class="sc">$</span>dqoj, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(base$dqof, base$dqoj, paired = TRUE): cannot
compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  base$dqof and base$dqoj
V = 179, p-value = 0.114
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(base<span class="sc">$</span>tempairef, base<span class="sc">$</span>tempairej, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(base$tempairef, base$tempairej, paired = TRUE):
cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  base$tempairef and base$tempairej
V = 524, p-value = 0.542
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Detectar variables con sufijos f y j</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>nombres_f <span class="ot">&lt;-</span> <span class="fu">grep</span>(<span class="st">"f$"</span>, <span class="fu">names</span>(base), <span class="at">value =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>nombres_j <span class="ot">&lt;-</span> <span class="fu">grep</span>(<span class="st">"j$"</span>, <span class="fu">names</span>(base), <span class="at">value =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Encontrar nombres base en común</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>pares_logicos <span class="ot">&lt;-</span> <span class="fu">intersect</span>(<span class="fu">sub</span>(<span class="st">"f$"</span>, <span class="st">""</span>, nombres_f), <span class="fu">sub</span>(<span class="st">"j$"</span>, <span class="st">""</span>, nombres_j))</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Ejecutar prueba de Wilcoxon para cada par</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>resultados_wilcoxon <span class="ot">&lt;-</span> <span class="fu">lapply</span>(pares_logicos, <span class="cf">function</span>(nombre_base) {</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  var_f <span class="ot">&lt;-</span> <span class="fu">paste0</span>(nombre_base, <span class="st">"f"</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  var_j <span class="ot">&lt;-</span> <span class="fu">paste0</span>(nombre_base, <span class="st">"j"</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Verificar que ambas variables existan en el data frame</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span>(var_f <span class="sc">%in%</span> <span class="fu">names</span>(base)) <span class="sc">||</span> <span class="sc">!</span>(var_j <span class="sc">%in%</span> <span class="fu">names</span>(base))) <span class="fu">return</span>(<span class="cn">NULL</span>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> base[[var_f]]</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> base[[var_j]]</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Verificar que ambos sean numéricos</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.numeric</span>(x) <span class="sc">||</span> <span class="sc">!</span><span class="fu">is.numeric</span>(y)) <span class="fu">return</span>(<span class="cn">NULL</span>)</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Eliminar NA en ambos</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>  completo <span class="ot">&lt;-</span> <span class="fu">complete.cases</span>(x, y)</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">sum</span>(completo) <span class="sc">&lt;</span> <span class="dv">3</span>) <span class="fu">return</span>(<span class="cn">NULL</span>)</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>  prueba <span class="ot">&lt;-</span> <span class="fu">wilcox.test</span>(x[completo], y[completo], <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">Par =</span> <span class="fu">paste</span>(var_f, <span class="st">"vs"</span>, var_j),</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_value =</span> <span class="fu">round</span>(prueba<span class="sc">$</span>p.value, <span class="dv">4</span>),</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">estadistico =</span> <span class="fu">as.numeric</span>(prueba<span class="sc">$</span>statistic)</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar resultados válidos y combinar</span></span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>resultados_wilcoxon <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, resultados_wilcoxon)</span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>kableExtra<span class="sc">::</span><span class="fu">kable</span>(resultados_wilcoxon)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Par</th>
<th style="text-align: right;">p_value</th>
<th style="text-align: right;">estadistico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">precipitacionf vs precipitacionj</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">tempairef vs tempairej</td>
<td style="text-align: right;">0.5420</td>
<td style="text-align: right;">524</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dbof vs dboj</td>
<td style="text-align: right;">0.0173</td>
<td style="text-align: right;">98</td>
</tr>
<tr class="even">
<td style="text-align: left;">dqof vs dqoj</td>
<td style="text-align: right;">0.1140</td>
<td style="text-align: right;">179</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Se realizaron pruebas de Wilcoxon para comparar distintas variables medidas en dos momentos o condiciones: aquellas con sufijo “f” y su correspondiente con sufijo “j”, lo cual permite evaluar si existen cambios significativos en la distribución de dichas variables. Esta prueba no asume normalidad y es adecuada para comparar muestras relacionadas (pareadas) cuando no se cumplen los supuestos de la prueba t.</p>
<p>En primer lugar, se aplicó la prueba de Wilcoxon de manera individual para las siguientes variables:</p>
<p>Para la variable DBO (Demanda Bioquímica de Oxígeno), se compararon los valores en los momentos “f” y “j”. El valor p obtenido fue de 0.0173, lo cual es menor al umbral de significancia de 0.05. Esto indica que existe una diferencia estadísticamente significativa en la distribución de la DBO entre los dos momentos, sugiriendo un posible cambio ambiental o de condiciones entre ambos periodos de observación.</p>
<p>En contraste, al evaluar la DQO (Demanda Química de Oxígeno) en los mismos términos, el valor p fue de 0.1140, lo que no alcanza significancia estadística. Esto sugiere que no hay evidencia suficiente para afirmar que haya habido un cambio relevante en la distribución de esta variable entre los momentos “f” y “j”, y por tanto, se podría considerar que esta característica se ha mantenido estable.</p>
<p>Algo similar se observó al analizar la temperatura del aire, comparando tempairef y tempairej, cuyo valor p fue de 0.5420, indicando con claridad la ausencia de diferencia significativa. Esta conclusión, además, se alinea con los resultados previos de normalidad para esta variable, donde se había determinado que ambas distribuciones eran compatibles con una distribución normal.</p>
<p>El cuadro resumen generado automáticamente mediante un procedimiento sistemático confirma estas observaciones y añade información adicional. Por ejemplo, se encontró que la precipitación sí presenta una diferencia altamente significativa entre los periodos, con un valor p de 0.0000 y un estadístico de prueba de 0, lo que sugiere un cambio muy marcado. Esto contrasta con otras variables como tempairef vs tempairej y dqof vs dqoj, cuyos resultados no muestran diferencias significativas.</p>
<p>En conjunto, estos resultados permiten concluir que algunas variables del sistema evaluado (como la DBO y la precipitación) presentan cambios significativos entre los dos momentos analizados, mientras que otras (como la DQO y la temperatura del aire) se mantienen relativamente estables. Estas diferencias pueden ser indicativas de variabilidad estacional, cambios ambientales o efectos de intervención, dependiendo del contexto específico del estudio.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prueba Chi-Cuadrado de Independencia (Variables Categóricas)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Es una prueba de hipótesis que se basa en variables categóricas para medir si existe una relación entre estas, de existir se recomienda combinar con la prueba V de Cramer para medir la fuerza de esta relación, se pide que las variables tengan una escala, ya sea ordinal o nominal.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Correlación de Pearson (Variables Cuantitativas)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Es utilizada para medir la correlación entre variables, dicha prueba muestra el valor de la fuerza de correlación en un rango de 0 a 1, siendo 0 nula correlación y 1 una correlación perfecta. Además mide la dirección de la correlación dado el signo.</p>
</div>
</div>
</section>
<section id="variables-de-febrero-y-julio" class="level3">
<h3 class="anchored" data-anchor-id="variables-de-febrero-y-julio">Variables de Febrero y Julio</h3>
<p>Primeramente se analizarán las distribuciones de los datos que tienen una observación en Febrero y una en Julio, para esto se harán pruebas pareadas asumiendo emparejamiento, esto debido a que la observación comparte ubicación.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prueba 1 : Comparación en la distribución de la Demanda Biológica de Oxígeno (DBO)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><span class="math inline">\(H_0\)</span> : No existe una diferencia entre la distribución de la DBO entre las recolecciones de datos de Febrero y Julio.</li>
<li><span class="math inline">\(H_1\)</span> : Si hay una diferencia significativa entre las distribuciones de DBO de Febrero y Julio.</li>
</ul>
<p>Como se mencionó anteriormente se asumirá que las variables son pareadas sin embargo no se puede asumir que la distribución de estas variables es Normal, por ello se aplicará la prueba de Wilcoxon pareada.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(base<span class="sc">$</span>dbof, base<span class="sc">$</span>dboj, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  base$dbof and base$dboj
V = 98, p-value = 0.01731
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>Al haberse obtenido un p-value de <span class="math inline">\(0.01731\)</span> se rechaza la hipótesis nula y se concluye que hay diferencias significativas entre la distribución del DBO según ambas fechas, esto tiene sentido al ser épocas distintas. Se sabe que en Costa Rica en febrero se encuentra la época más seca correspondiente al verano mientras que en julio comienza la época lluviosa.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prueba 2 : Comparación en la distribución de la Demanda Química de Oxígeno (DQO)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><span class="math inline">\(H_0\)</span> : No existe una diferencia entre la distribución de la DQO entre las recolecciones de datos de Febrero y Julio.</li>
<li><span class="math inline">\(H_1\)</span> : Si hay una diferencia significativa entre las distribuciones de DQO de Febrero y Julio.</li>
</ul>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(base<span class="sc">$</span>dqof, base<span class="sc">$</span>dqoj, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(base$dqof, base$dqoj, paired = TRUE): cannot
compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  base$dqof and base$dqoj
V = 179, p-value = 0.114
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>En este caso al ser el p-value mayor a <span class="math inline">\(0.05\)</span> no hay suficiente evidencia para rechazar la hipótesis nula por lo que no se puede concluir que la distribución de la Demanda Química del Oxígeno para los meses de Febrero y Julio son distintos. Dado que este valor no dió como se esperaba se realizará la correlación de pearson para ver si existe relación entre ellas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(base<span class="sc">$</span>dqof, base<span class="sc">$</span>dqoj, <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  base$dqof and base$dqoj
t = 1.0223, df = 30, p-value = 0.3148
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.1765040  0.5001757
sample estimates:
      cor 
0.1834825 </code></pre>
</div>
</div>
<p>Este resultado indica que existe cierta relación lineal entre estas variables. (Falta investigar en los antecedentes pero se que en el modelo de caudales se debían considerar el rezago de 1 a 6 meses además de 12 meses para las variables por el año hidrológico, tal vez sea una razón por la que existe una correlación entre estas variables).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prueba 3: Correlación entre oxígeno disuelto y saturación de oxígeno
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><span class="math inline">\(H_0\)</span>: No existe correlación entre el oxígeno disuelto y la saturación de oxígeno.</li>
<li><span class="math inline">\(H_1\)</span>: Existe una correlación significativa entre el oxígeno disuelto y la saturación de oxígeno.</li>
</ul>
</div>
</div>
<p>Ambas son numéricas y relacionadas físicamente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(base<span class="sc">$</span>oxigeno, base<span class="sc">$</span>sat_oxigen, <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(base$oxigeno, base$sat_oxigen, method =
"spearman"): Cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  base$oxigeno and base$sat_oxigen
S = 1172.9, p-value = 4.186e-10
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.8357268 </code></pre>
</div>
</div>
<p>El coeficiente de correlación de Spearman fue <span class="math inline">\(\rho = 0.8357\)</span> con un valor <span class="math inline">\(p = 4.19 \times 10^{-10}\)</span>, lo cual indica una correlación positiva muy fuerte y estadísticamente significativa entre el oxígeno disuelto y la saturación de oxígeno en el agua. Dado que el valor p es mucho menor que 0.05, se rechaza la hipótesis nula (<span class="math inline">\(H_0\)</span>) y se concluye que existe una relación monótona significativa entre ambas variables. Esto es consistente con la teoría físico-química, ya que la saturación de oxígeno depende directamente del contenido de oxígeno disuelto respecto a la capacidad máxima del agua para disolverlo a cierta temperatura y presión.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prueba 4: Correlación entre fosfatos y clorofila-a
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><span class="math inline">\(H_0\)</span>: No existe correlación entre la concentración de fosfatos y la clorofila-a en el agua.</li>
<li><span class="math inline">\(H_1\)</span>: Existe una correlación significativa entre los fosfatos y la clorofila-a.</li>
</ul>
</div>
</div>
<p>Podría indicar efecto de nutrientes en productividad:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(base<span class="sc">$</span>fosfatos, base<span class="sc">$</span>chla_agua, <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(base$fosfatos, base$chla_agua, method =
"spearman"): Cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  base$fosfatos and base$chla_agua
S = 13662, p-value = 0.8407
alternative hypothesis: true rho is not equal to 0
sample estimates:
        rho 
-0.03158412 </code></pre>
</div>
</div>
<p>En este caso, el coeficiente de correlación de Spearman fue <span class="math inline">\(\rho = -0.0316\)</span>, con un valor <span class="math inline">\(p = 0.8407\)</span>. Esto indica una correlación extremadamente débil y no significativa entre la concentración de fosfatos y la clorofila-a. Dado que el valor p es mucho mayor que 0.05, no se rechaza la hipótesis nula (<span class="math inline">\(H_0\)</span>), lo que sugiere que no hay evidencia estadística de una relación entre estas dos variables en el conjunto de datos analizado. Esto podría deberse a que otros factores (como la luz, nitrógeno u otras condiciones ambientales) están modulando la producción de fitoplancton más que el fósforo, o también a limitaciones en el tamaño muestral o a efectos de saturación.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prueba 5: Correlación entre nitratos y coliformes fecales
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><span class="math inline">\(H_0\)</span>: No existe correlación entre la concentración de nitratos y los coliformes fecales.</li>
<li><span class="math inline">\(H_1\)</span>: Existe una correlación significativa entre nitratos y coliformes fecales.</li>
</ul>
</div>
</div>
<p>Puede sugerir contaminación orgánica:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(base<span class="sc">$</span>nitratos, base<span class="sc">$</span>colifecalj, <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(base$nitratos, base$colifecalj, method =
"spearman"): Cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  base$nitratos and base$colifecalj
S = 15222, p-value = 0.339
alternative hypothesis: true rho is not equal to 0
sample estimates:
       rho 
-0.1493776 </code></pre>
</div>
</div>
<p>El coeficiente de Spearman fue <span class="math inline">\(\rho = -0.1494\)</span> con un valor <span class="math inline">\(p = 0.339\)</span>, lo cual indica una correlación débil y no significativa entre la concentración de nitratos y la presencia de coliformes fecales en el agua. Aunque ambos pueden estar asociados a fuentes de contaminación orgánica, en este conjunto de datos no se encuentra evidencia estadística suficiente para rechazar la hipótesis nula (<span class="math inline">\(H_0\)</span>). Esto sugiere que la presencia de coliformes fecales no necesariamente está asociada a una mayor concentración de nitratos en las muestras evaluadas.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prueba 6: Correlación entre dureza y carbonatos
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><span class="math inline">\(H_0\)</span>: No existe correlación entre la dureza del agua y la concentración de carbonatos.</li>
<li><span class="math inline">\(H_1\)</span>: Existe una correlación significativa entre dureza y carbonatos.</li>
</ul>
</div>
</div>
<p>Ambas relacionadas con composición iónica del agua:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(base<span class="sc">$</span>dureza, base<span class="sc">$</span>carbonatos, <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(base$dureza, base$carbonatos, method = "spearman"):
Cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  base$dureza and base$carbonatos
S = 2195.6, p-value = 0.2193
alternative hypothesis: true rho is not equal to 0
sample estimates:
     rho 
0.249357 </code></pre>
</div>
</div>
<p>El coeficiente de Spearman fue <span class="math inline">\(\rho = 0.2494\)</span> con un valor <span class="math inline">\(p = 0.2193\)</span>, lo cual indica una correlación positiva débil, pero no estadísticamente significativa entre la dureza del agua y la concentración de carbonatos. Aunque se esperaría una relación positiva dada su relación con la composición iónica del agua (especialmente por la presencia de calcio y magnesio), los resultados actuales no permiten concluir que exista una asociación consistente entre estas dos variables en el conjunto de datos analizado.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prueba 7: Correlación entre salinidad y sulfatos (SO<span class="math inline">\(_4^{2-}\)</span>)
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><span class="math inline">\(H_0\)</span>: No existe correlación entre la salinidad y la concentración de sulfatos en el agua.</li>
<li><span class="math inline">\(H_1\)</span>: Existe una correlación significativa entre salinidad y sulfatos.</li>
</ul>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(base<span class="sc">$</span>salinidad, base<span class="sc">$</span>SO42, <span class="at">method =</span> <span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(base$salinidad, base$SO42, method = "spearman"):
Cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  base$salinidad and base$SO42
S = 265.42, p-value = 0.04399
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.5260399 </code></pre>
</div>
</div>
<p>Aquí se obtuvo un coeficiente de Spearman <span class="math inline">\(\rho = 0.5260\)</span> y un valor <span class="math inline">\(p = 0.04399\)</span>, indicando una correlación positiva moderada y estadísticamente significativa entre la salinidad y la concentración de sulfatos en el agua. Dado que el valor p es menor al umbral de significancia de 0.05, se rechaza la hipótesis nula (<span class="math inline">\(H_0\)</span>) y se concluye que existe una asociación significativa entre ambas variables. Esto es coherente con lo esperado, ya que los sulfatos son uno de los iones que contribuyen a la salinidad del agua, especialmente en ambientes con influencia marina o mezcla salobre.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>